name: Frontend CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 'current', 'latest' ]
    name: Build on Node ${{ matrix.Node }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node ${{ matrix.Node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.Node }}
          cache: npm
          cache-dependency-path: viewer-frontend/package-lock.json

      - name: Build with Node
        working-directory: viewer-frontend
        run: npm run build

#      - name: Upload Artifact
#        uses: actions/upload-artifact@v3
#        if: matrix.Node == 'latest'
#        with:
#          name: frontend
#          path: "viewer-frontend/.svelte-kit/build/*"
